#!/bin/bash
path=$(fzf)
path_length=${#path}
if [ $path_length -gt 0 ];then
	echo "relative path is "$path
	echo "absolute path is "$(pwd)"/"$path
    file_message=`file $path`
    echo "$file_message"


    if [[ $file_message == *"HTML"* ]]
    then
	    google-chrome-stable $path
    elif [[ $file_message == *"text"* ]]
    then
	    vim $path
            history -s "vim $path"
    fi
fi 
